services:
    minio:
        image: minio/minio:latest
        container_name: minio
        command: server /data --console-address ":9001"
        ports:
            - "9000:9000" # S3 API
            - "9001:9001" # Web Console
        networks:
            - backend
        volumes:
            - "minio_data:/data"
        environment:
            - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
            - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
            # Pointing directly to the ports
            - MINIO_SERVER_URL=http://${DOMAIN_NAME}:9000
            - MINIO_BROWSER_REDIRECT_URL=http://${DOMAIN_NAME}:9001
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
            interval: 30s
            timeout: 20s
            retries: 3
            start_period: 30s
        restart: unless-stopped

    minio-setup:
        image: minio/mc:latest
        container_name: minio-setup
        depends_on:
            minio:
                condition: service_healthy 
        networks:
            - backend
        entrypoint: >
            /bin/sh -c "
            mc alias set myminio http://minio:9000 ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY};
            mc mb myminio/project-a --ignore-existing;
            mc mb myminio/project-b --ignore-existing;
            exit 0;
            "

networks:
    backend:
        driver: bridge

volumes:
    minio_data: